var posts = [
  {
    "imagem": "https://picsum.photos/id/100/348/185",
    "titulo": "Praia dos Sonhos",
    "valor": "R$ 3.500,00",
    "descricao": "1 quarto | 1 banheiro | 1 vaga de garagem",
    "autor": "Gabriel Gostinski",
    "data": "15 Out 2024",
    "imagem_post": "https://picsum.photos/id/100/1110/590",
    "texto": "Um paraíso onde o mar cristalino encontra areias douradas, criando o cenário perfeito para relaxar e se conectar com a natureza. Com suas águas calmas e paisagens de tirar o fôlego, a Praia dos Sonhos é o destino ideal para quem busca tranquilidade e momentos inesquecíveis à beira-mar."
  },
  {
    "imagem": "https://picsum.photos/id/200/348/185",
    "titulo": "Monte Cristalino",
    "valor": "R$ 4.000,00",
    "descricao": "4 quarto | 2 banheiro | 1 vaga de garagem",
    "autor": "Gabriel Gostinski",
    "data": "15 Out 2024",
    "imagem_post": "https://picsum.photos/id/200/1110/590",
    "texto": "Um refúgio de inverno cercado por paisagens deslumbrantes. Com picos cobertos de neve e ar puro das montanhas, o Monte Cristalino é perfeito para quem ama aventuras no frio ou momentos tranquilos junto à natureza. Um destino que combina beleza e serenidade em cada detalhe.",
  },
  {
    "imagem": "https://picsum.photos/id/43/348/185",
    "titulo": "Céu de Luzes",
    "valor": "R$ 5.750,00",
    "descricao": "2 quarto | 1 banheiro | 2 vagas de garagem",
    "autor": "Gabriel Gostinski",
    "data": "15 Out 2024",
    "imagem_post": "https://picsum.photos/id/43/1110/590",
    "texto": "Uma cidade que não dorme, onde a vida ganha um novo ritmo à noite. As ruas iluminadas revelam o charme moderno das metrópoles, com arranha-céus refletindo luzes que parecem tocar o céu. Seja para passear, explorar ou apenas contemplar, esse é o destino ideal para quem busca energia vibrante e beleza urbana.",
  },
  {
    "imagem": "https://picsum.photos/id/49/348/185",
    "titulo": "Santuário Egeu",
    "valor": "R$ 4.800,00",
    "descricao": "4 quarto | 1 banheiro | 1 vaga de garagem",
    "autor": "Gabriel Gostinski",
    "data": "15 Out 2024",
    "imagem_post": "https://picsum.photos/id/49/1110/590",
    "texto": "Com casinhas brancas contrastando com o azul profundo do mar, essa cidade encanta pela simplicidade e charme. Cada ruela conta uma história, enquanto o horizonte revela a união perfeita entre céu e mar. Um destino onde o tempo parece parar, ideal para relaxar e se reconectar com a essência da vida.",
  },
  {
    "imagem": "https://picsum.photos/id/57/348/185",
    "titulo": "Viela da Toscana",
    "valor": "R$ 2.000,99",
    "descricao": "3 quarto | 2 banheiro | 0 vagas de garagem",
    "autor": "Gabriel Gostinski",
    "data": "15 Out 2024",
    "imagem_post": "https://picsum.photos/id/57/1110/590",
    "texto": "Imagine-se caminhando por ruas estreitas, ladeadas por prédios antigos e varandas floridas. A cidade exala romantismo e charme, com cafés ao ar livre, onde o aroma de café fresco e massas artesanais preenchem o ar. Um pedaço da Itália que celebra a beleza dos detalhes e o prazer de viver.",
  },
  {
    "imagem": "https://picsum.photos/id/74/348/185",
    "valor": "R$ 1.500,00",
    "descricao": "1 quarto | 1 banheiro | 1 vaga de garagem",
    "titulo": "Horizonte de Conexões",
    "autor": "Gabriel Gostinski",
    "data": "15 Out 2024",
    "imagem_post": "https://picsum.photos/id/74/1110/590",
    "texto": "À beira do mar, uma cidade moderna se ergue, conectada por uma ponte imponente que parece abraçar o horizonte. Um cenário que combina a serenidade do oceano com a energia de uma metrópole, perfeito para quem busca o equilíbrio entre natureza e modernidade.",
  },
  {
    "imagem": "https://picsum.photos/id/122/348/185",
    "titulo": "Palácio da História",
    "descricao": "5 quarto | 2 banheiro | 3 vagas de garagem",
    "valor": "R$ 5.540,00",
    "autor": "Gabriel Gostinski",
    "data": "15 Out 2024",
    "imagem_post": "https://picsum.photos/id/122/1110/590",
    "texto": "Com arquitetura imponente e inspiração neoclássica, este local carrega consigo um ar de nobreza e poder. Suas colunas brancas refletem a elegância de uma época passada, enquanto os jardins ao redor convidam para momentos de reflexão e contemplação.",
  },
  {
    "imagem": "https://picsum.photos/id/142/348/185",
    "titulo": "Fortaleza Real",
    "descricao": "4 quarto | 1 banheiro | 2 vagas de garagem",
    "valor": "R$ 9.560,00",
    "autor": "Gabriel Gostinski",
    "data": "15 Out 2024",
    "imagem_post": "https://picsum.photos/id/142/1110/590",
    "texto": "Majestoso e cheio de história, este castelo se ergue sobre colinas verdes, como guardião de tempos antigos. Suas torres e muralhas revelam segredos de reis e rainhas, enquanto o interior oferece um vislumbre da vida na realeza. Um lugar que faz você se sentir dentro de um conto de fadas.",
  },
  {
    "imagem": "https://picsum.photos/id/164/348/185",
    "titulo": "Canais do Encanto",
    "descricao": "3 quarto | 2 banheiro | 0 vagas de garagem",
    "valor": "R$ 3.500,00",
    "autor": "Gabriel Gostinski",
    "data": "15 Out 2024",
    "imagem_post": "https://picsum.photos/id/164/1110/590",
    "texto": "Essa cidade é um verdadeiro labirinto de canais e pontes encantadoras. Barcos deslizam pelas águas tranquilas, enquanto as fachadas coloridas refletem no espelho líquido. Um destino romântico e único, onde cada canto é digno de uma pintura.",
  },
  {
    "imagem": "https://picsum.photos/id/195/348/185",
    "titulo": "Noite Neon",
    "descricao": "1 quarto | 1 banheiro | 1 vaga de garagem",
    "valor": "R$ 6.200,00",
    "autor": "Gabriel Gostinski",
    "data": "15 Out 2024",
    "imagem_post": "https://picsum.photos/id/195/1110/590",
    "texto": "Sob as luzes vibrantes dos letreiros de neon, essa rua ganha vida como em um filme futurista. As pessoas caminham entre lojas e restaurantes, enquanto o aroma de comida de rua invade o ar. Um lugar onde tradição e modernidade se encontram em perfeita harmonia.",
  },
  {
    "imagem": "https://picsum.photos/id/199/348/185",
    "titulo": "Paraíso Tropical",
    "descricao": "3 quarto | 1 banheiro | 2 vagas de garagem",
    "valor": "R$ 5.780,00",
    "autor": "Gabriel Gostinski",
    "data": "15 Out 2024",
    "imagem_post": "https://picsum.photos/id/199/1110/590",
    "texto": "Águas cristalinas, coqueiros balançando ao vento e uma areia dourada que parece infinita. Essa praia é o retrato da beleza natural do Brasil, com um clima acolhedor e um pôr do sol que ilumina o coração. Perfeita para relaxar ou se aventurar nas ondas.",
  },
  {
    "imagem": "https://picsum.photos/id/234/348/185",
    "titulo": "Paris dos Sonhos",
    "descricao": "5 quarto | 2 banheiro | 2 vagas de garagem",
    "valor": "R$ 7.900,00",
    "autor": "Gabriel Gostinski",
    "data": "15 Out 2024",
    "imagem_post": "https://picsum.photos/id/234/1110/590",
    "texto": "A Torre Eiffel é o símbolo máximo do romantismo e da elegância parisiense. Com sua estrutura imponente, ela domina o céu da Cidade Luz, encantando visitantes de todo o mundo. Seja de dia ou à noite, seu charme é inconfundível, tornando-a o cenário perfeito para momentos inesquecíveis.",
  }
];
